name: "Nix"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build packages
      run: |
        set -o pipefail
        echo $(nix eval --impure --raw --expr 'builtins.currentSystem')
        echo echo $(nix flake show --json)
        export PLATFORM="$(nix eval --impure --raw --expr 'builtins.currentSystem')"
        nix flake show --json | jq  ".packages.\"$PLATFORM\"|keys[]"| xargs -I {} nix build .#{}
