name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        export PLATFORM="$(nix eval --impure --raw --expr 'builtins.currentSystem')"
        nix flake show --json | jq  ".packages.\"$PLATFORM\"|keys[]"| xargs -I {} nix build .#{}
